name: DEPLOY TO STAGING(-final)

on:
  push:
    branches:
      - main

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build

      # Replace asset paths in the built files
      - name: Update Asset Paths
        run: |
          find ./dist -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -exec sed -i 's|/assets/|/2024/project3/t8/assets/|g' {} +

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "project3.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/2024/project3/t8"